### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by alexrvs** [lygav/php-slackbot#2]
PHP Fatal error:  Uncaught Error: Class 'lygav\slackbot\SlackBot' not found

**Comment by lygav** [comment]
Hi @alexandervas , is it possible for you to share a little bit more about when/ how you are getting this error?
Maybe couple of words about your environment/installation method (eg. have you used composer)?
Because it looks like there might be a problem in how the project is structured/set-up.

**Comment by alexrvs** [comment]
thanks, already fixed it

**Comment by lygav** [comment]
Great. Closing it then.
