### ISSUE TITLE
__invoke problem

### ISSUE THREAD

**Issue by alexrvs** [lygav/php-slackbot#3]
I have another problem with
channel_not_found in /vendor/lygav/php-slackbot/src/SlackBot.php:97
my code is  $bot = new Slackbot("https://hooks.slack.com/services/your/incoming/hook");
$bot->text($message)->toPerson('@alexvas')->send();
and get error:
PHP Fatal error:  Uncaught lygav\slackbot\Exceptions\SlackRequestException: channel_not_found in /home/user/public_html/slackbot.loc/www/vendor/lygav/php-slackbot/src/SlackBot.php:97
Stack trace:
#0 /home/user/public_html/slackbot.loc/www/vendor/lygav/php-slackbot/src/SlackBot.php(77): lygav\slackbot\SlackBot->transfer(Object(lygav\slackbot\SlackRequest))
#1 /home/user/public_html/slackbot.loc/www/index.php(42): lygav\slackbot\SlackBot->send()
#2 /home/user/public_html/slackbot.loc/www/index.php(49): AlexBot->sendMessage('Say hello!!!')
#3 {main}
  thrown in /home/user/public_html/slackbot.loc/www/vendor/lygav/php-slackbot/src/SlackBot.php on line 97
user@user-1115:~/public_html/slackbot.loc/www$ php index.php
PHP Fatal error:  Uncaught lygav\slackbot\Exceptions\SlackRequestException: channel_not_found in /home/user/public_html/slackbot.loc/www/vendor/lygav/php-slackbot/src/SlackBot.php:97
Stack trace:
#0 /home/user/public_html/slackbot.loc/www/vendor/lygav/php-slackbot/src/SlackBot.php(77): lygav\slackbot\SlackBot->transfer(Object(lygav\slackbot\SlackRequest))
#1 /home/user/public_html/slackbot.loc/www/index.php(39): lygav\slackbot\SlackBot->send()
#2 /home/user/public_html/slackbot.loc/www/index.php(46): AlexBot->sendMessage('Say hello!!!')
#3 {main}
  thrown in /home/user/public_html/slackbot.loc/www/vendor/lygav/php-slackbot/src/SlackBot.php on line 97

**Comment by alexrvs** [comment]
Maybe it, because i make wrapper for SlackBot class

**Comment by lygav** [comment]
Hi @alexandervas , what you see is actually a Slack API error message.
Can you please confirm that you actually changed the incoming hook url in the
Slackbot constructor?

**Comment by alexrvs** [comment]
Fixed it )), I forgot to added from method

**Comment by lygav** [comment]
Super. I probably should add more descriptive error messages for such cases
